# Data Exploration & Analysis of Heart Failture Dataset

#### [UCI Heart Failure](https://archive.ics.uci.edu/ml/datasets/Heart+failure+clinical+records)

### Import packages

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib inline
import matplotlib.mlab as mlab

### Load Data

In [4]:
HF= pd.read_csv('/Users/silviacatalina/Google Drive/BethelTech/GitHub/FinalProject/Data/healthcare-dataset-stroke-data.csv')
HF.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

## Column description for thirteen (13) clinical features: 

- age: age of the patient (years) 
- anaemia: decrease of red blood cells or hemoglobin (boolean) 
- high blood pressure: if the patient has hypertension (boolean) 
- creatinine phosphokinase (CPK): level of the CPK enzyme in the blood (mcg/L) 
- diabetes: if the patient has diabetes (boolean) 
- ejection fraction: percentage of blood leaving the heart at each contraction (percentage) 
- platelets: platelets in the blood (kiloplatelets/mL) 
- sex: woman or man (binary) 
- serum creatinine: level of serum creatinine in the blood (mg/dL) 
- serum sodium: level of serum sodium in the blood (mEq/L) 
- smoking: if the patient smokes or not (boolean) 
- time: follow-up period (days) 
- [target] death event: if the patient deceased during the follow-up period (boolean)

## Correlation Matrix

In [5]:
HF.corr(method='pearson').style.format("{:.2}").background_gradient(cmap=plt.get_cmap('coolwarm'), axis=1)

__*None of the collumns are correlated*__